### ISSUE TITLE
syncoid fails recursive replication after initial execution

### ISSUE THREAD

**Issue by lalloni** [jimsalterjrs/sanoid#58]
Suppose you have:

```
pool0
pool0/container
pool0/container/filesystem1
pool0/container/filesystem2
pool0/container/filesystem3
pool1
```

Then you run `syncoid -r pool0/container pool1/container` and that results (after ending succesfuly) in having:

```
pool0
pool0/container
pool0/container@syncoid_host1_2016-11-01:09:12:31
pool0/container/filesystem1
pool0/container/filesystem1@syncoid_host1_2016-11-01:09:12:44
pool0/container/filesystem2
pool0/container/filesystem2@syncoid_host1_2016-11-01:09:15:11
pool0/container/filesystem3
pool0/container/filesystem3@syncoid_host1_2016-11-01:09:20:32
pool1
pool1/container
pool1/container/filesystem1
pool1/container/filesystem2
pool1/container/filesystem3
```

Some time passes and then you try to update the copy running again `syncoid -r pool0/container pool1/container`, but that fails with:

```
Sending incremental pool0/container@syncoid_host1_2016-11-01:09:12:31 ... syncoid_host1_2016-11-01:09:32:39 (~ 4 KB):
1,52kB 0:00:00 [5,88kB/s] [==============================================>                                                                             ] 38%            
cannot open 'pool0/container@syncoid_host1_2016-11-01:09:12:31': dataset does not exist
cannot create snapshot 'pool0/container@syncoid_host1_2016-11-01:09:12:31@syncoid_host1_2016-11-01:09:32:40': multiple '@' delimiters in name
CRITICAL ERROR:  /usr/bin/sudo /sbin/zfs snapshot pool0/container@syncoid_host1_2016-11-01:09:12:31@syncoid_tulkas_2016-11-01:09:32:40
 failed: 256 at /usr/local/bin/syncoid line 724.
```

Apparently recursive syncoid finds self-managed snapshots as child filesystems and then try to replicate them (which it shouldn't) but then it fails at that because it first destroys such snapshots (as it should, after replicating the corresponding filesystem).

**Comment by jimsalterjrs** [comment]
What platform is this on?

> cannot create snapshot 'pool0/container@syncoid_host1_2016-11-01:09:12:31@syncoid_host1_2016-11-01:09:32:40': multiple '@' delimiters in name

^^ that is a brand new one on me, and should be entirely impossible.  Syncoid knows the difference between snapshots and datasets.

> recursive syncoid finds self-managed snapshots as child filesystems

Again, this is a weird and brand-new one on me. People (very much including me personally) generate manual snapshots of all sorts of datasets, child and otherwise, all the time; syncoid neither knows nor cares who took the snapshot.  Syncoid does create its own replication snapshots to ensure both that the most recent production data is replicate and to attempt to ensure that any _deletion_ of non-syncoid snapshots won't break a chain of incremental replications from one host to another, but it literally doesn't bother itself about any others in between.

While we're at it, can you please do a syncoid --version and paste here?  I've never seen this bug in any prior version of syncoid either, but I want to make sure I know what we're looking at.

**Comment by lalloni** [comment]
Running on Ubuntu 14.04.

```
% syncoid --version
Syncoid version: 1.4.7
```

**Comment by lalloni** [comment]
I've found that for some forgotten reason my source pool had `listsnaps=on` set, that causes `zfs list` to include snapshots, and given syncoid assumes `zfs list` returns only filesystems then it took snapshots for filesystems. So... it seems syncoid doesn't know the difference between a snapshot and a dataset.

**Comment by jimsalterjrs** [comment]
Note to self: use `zfs list -t filesystem` where appropriate to prevent this issue where people have set `listsnaps=on`.

@lalloni thanks for sharing the bit about listsnaps=on. I didn't even known that was a _thing._  I'll fix this in an update soon, hopefully later today.

**Comment by GregorKopka** [comment]
@jimsalterjrs using `-t filesystem` would lead to skipping volumes, might not be what you intend.

**Comment by mailinglists35** [comment]
@GregorKopka you can do `zfs list -t filesystem,volume` in a single invocation

**Comment by GregorKopka** [comment]
@mailinglists35 my comment was aimed at the comment from @jimsalterjrs to hint him to not introduce another bug by fixing this one in a flawed way.

**Comment by jimsalterjrs** [comment]
(note: this was closed because I fixed it with `-t filesystem,volume` on May 3, not because I got bored with it on May 3)

**Comment by fold0** [comment]
I've ran into the same issue with listsnaps on latest version f6519c0, I don't think it was fixed

**Comment by canove** [comment]
> I've ran into the same issue with listsnaps on latest version [f6519c0](https://github.com/jimsalterjrs/sanoid/commit/f6519c0aea4c624161f92a1304943d1c60e714bc), I don't think it was fixed

I'm facing the same issue with sanoi. For me, syncoid recursive options seems to works well with "listsnapshots=on". Sanoid don't:
`CRITICAL ERROR: /sbin/zfs snapshot rpool/data/vm-100-disk-0@autosnap_2019-01-30_16:26:08_monthly@autosnap_2019-01-30_16:26:09_hourly failed, 256 at /usr/sbin/sanoid line 537.
cannot create snapshot 'rpool/data/vm-100-disk-0@autosnap_2019-01-30_16:26:08_monthly@autosnap_2019-01-30_16:26:09_frequently': multiple '@' and/or '#' delimiters in name`

I'm using sincoid on Proxmox 5.3
`root@pve-bkp:/backup/config# sanoid --version
/usr/sbin/sanoid version 2.0.0
`
Thanks for the great tool! 👍
